
package com.demo.spring.webservice.soap.client.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountServiceName", targetNamespace = "http://ws.test.spring.com/", wsdlLocation = "http://localhost:8080/Spring_Test/services/AccountService?wsdl")
public class AccountServiceName
    extends Service
{

    private final static URL ACCOUNTSERVICENAME_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTSERVICENAME_EXCEPTION;
    private final static QName ACCOUNTSERVICENAME_QNAME = new QName("http://ws.test.spring.com/", "AccountServiceName");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Spring_Test/services/AccountService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTSERVICENAME_WSDL_LOCATION = url;
        ACCOUNTSERVICENAME_EXCEPTION = e;
    }

    public AccountServiceName() {
        super(__getWsdlLocation(), ACCOUNTSERVICENAME_QNAME);
    }

    public AccountServiceName(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTSERVICENAME_QNAME, features);
    }

    public AccountServiceName(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTSERVICENAME_QNAME);
    }

    public AccountServiceName(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTSERVICENAME_QNAME, features);
    }

    public AccountServiceName(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountServiceName(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountWS
     */
    @WebEndpoint(name = "AccountServicePort")
    public AccountWS getAccountServicePort() {
        return super.getPort(new QName("http://ws.test.spring.com/", "AccountServicePort"), AccountWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountWS
     */
    @WebEndpoint(name = "AccountServicePort")
    public AccountWS getAccountServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.test.spring.com/", "AccountServicePort"), AccountWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTSERVICENAME_EXCEPTION!= null) {
            throw ACCOUNTSERVICENAME_EXCEPTION;
        }
        return ACCOUNTSERVICENAME_WSDL_LOCATION;
    }

}
