
package com.demo.spring.webservice.soap.client.api;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountWS", targetNamespace = "http://ws.test.spring.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertAccount", targetNamespace = "http://ws.test.spring.com/", className = "com.spring.test.ws.client.api.InsertAccount")
    @ResponseWrapper(localName = "insertAccountResponse", targetNamespace = "http://ws.test.spring.com/", className = "com.spring.test.ws.client.api.InsertAccountResponse")
    public void insertAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        Account arg0);

    /**
     * 
     * @param file
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "upload", targetNamespace = "http://ws.test.spring.com/", className = "com.spring.test.ws.client.api.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://ws.test.spring.com/", className = "com.spring.test.ws.client.api.UploadResponse")
    public boolean upload(
        @WebParam(name = "file", targetNamespace = "")
        CxfFileWrapper file);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.spring.test.ws.client.api.CxfFileWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://ws.test.spring.com/", className = "com.spring.test.ws.client.api.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://ws.test.spring.com/", className = "com.spring.test.ws.client.api.DownloadResponse")
    public CxfFileWrapper download(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<com.spring.test.ws.client.api.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://ws.test.spring.com/", className = "com.spring.test.ws.client.api.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://ws.test.spring.com/", className = "com.spring.test.ws.client.api.GetAccountsResponse")
    public List<Account> getAccounts(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param accountId
     * @return
     *     returns com.spring.test.ws.client.api.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws.test.spring.com/", className = "com.spring.test.ws.client.api.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws.test.spring.com/", className = "com.spring.test.ws.client.api.GetAccountResponse")
    public Account getAccount(
        @WebParam(name = "accountId", targetNamespace = "")
        int accountId);

}
