SET DATABASE SQL SYNTAX ORA TRUE;

--- ENV_PROP---
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (100,'ENV','DEV1','Y','Y','ns49508',to_date('10-MAY-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1153,'YEAR_END_MONTH','06','Y','Y','rd24197',to_date('04-JUL-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1110,'GEN_CDN_URL','https://gencdn-sit.gsrena.ssmb.com:20539/dev','Y','Y','ns49508',to_date('10-JUN-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1112,'LOGIN_BACKDOOR_ENABLED','Y','Y','Y','ns49508',to_date('10-JUN-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1120,'SSO_URL','https://fnbkbone-sit.gsrena.ssmb.com:30899/dev/fbbop-web/','Y','Y','ns49508',to_date('02-JUL-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (3152,'SEND_MAX_CWD','Y','Y','Y','am59862',to_date('13-AUG-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1160,'APP_LDAP_ROLE','FNBKBONE-OPSPORTAL-MP;FNBKBONE-AEPORTAL-MP;FNBKBONE-ADJUSTMENTS-MP;FFS-RPT-FRO-MP;FFS-RPT-GFDS-MP;FFS-RPT-ENDUSER-MP;INQUIRY-RPT-SUPPORT-MP;FFS-RPT-TECH-DI-MP;FNBKBONE-TRIGGER-ROLE-MP;FNBKBONE-OPS-SUPERVISOR-MP','Y','Y','am59862',to_date('12-SEP-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1170,'LM_SUB_FEED_TYP','GRM;TPR;RCE','Y','Y','am59862',to_date('22-SEP-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1190,'LM_FRS_RECON','Y',null,null,null,null,null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1130,'SGL_TRIGGERING_ENABLED','Y','Y','N','hk58902',to_date('22-AUG-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1001,'LDAP_LAD_ID','fnbkbone_portal-dev','Y','Y','vm24196',to_date('25-SEP-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1002,'LDAP_LAD_PWD','tbOhpvUa','Y','Y','vm24196',to_date('25-SEP-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1131,'LDAP_APP_ID','fnbkbone','Y','Y','vm24196',to_date('25-SEP-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1133,'LDAP_RETRY_LIMIT','3','Y','Y','vm24196',to_date('25-SEP-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1135,'LOGOUT_SITEMINDER_URL','https://fnbkbone-sit.gsrena.ssmb.com:30899/siteminderagent/forms/logout.html','Y','Y','sm98036',to_date('02-OCT-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1138,'SESSION_TOKEN','14330030614fnbkbone_portal-dev','Y','N','vm24196',to_date('31-OCT-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1139,'LDAP_URL','http://lad-dev.ny.ssmb.com:81/','Y','Y','vm24196',to_date('15-NOV-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1140,'EMAIL_HOSTNAME','localhost','Y','Y','sm98036',to_date('16-DEC-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1141,'EMAIL_PORTNO','25','Y','Y','sm98036',to_date('16-DEC-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1142,'NO_OF_DAYS_LOOKBACK_FOR_SLA','3','Y','Y','sm98036',to_date('14-FEB-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1143,'J2B_REPORT_PATH','/var/app/epsdev/inbound/FBB/dev/J2B/op_trg_files/j2b_oprtnl_rpts','Y','Y','sm98036',to_date('14-FEB-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1144,'LM_REPORT_PATH','/var/app/fbbdev/opsportal/reports/dev1/lm','Y','Y','am59862',to_date('14-FEB-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1145,'PCF_APP_URL','https://localhost:8111/dev/pcfapp-web/','Y','Y','sm98036',to_date('14-FEB-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1146,'PCF_APP_URL_NAM','https://localhost:8111/dev/pcfapp-web/','Y','Y','sm98036',to_date('14-FEB-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1147,'PCF_APP_URL_APAC','https://localhost:8111/dev/pcfapp-web/','Y','Y','sm98036',to_date('14-FEB-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1148,'APPROVE_FAEM_URL','https://fnbkbone-sit.gsrena.ssmb.com:30899/sitgl/ProcessPortal','Y','Y','ns49508',to_date('26-MAR-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1180,'TRIGGER_BY_LVID','N','Y','Y','nv04763',to_date('07-OCT-13','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1151,'FBB_CSI_ID','localhost','Y','Y','am86454',to_date('16-JUN-14','DD-MON-RR'),null,null);
INSERT into ENV_PROP (ENV_PROP_ID,ENV_NM,ENV_VAL,ACTV_IND,CAN_CACHED,CREA_BY,CREA_DT,MDFY_BY,MDFY_DT) values (1142,'NO_OF_DISPLAY_ROWS','750','Y','Y','sm98036',to_date('24-JUN-14','DD-MON-RR'),null,null);
--ENV_PROP--

--TEST--
INSERT into TEST (REPORT_ID, REPORT_NAME, CREATED_BY, CREATION_TIME) values ('1', 'Report1', 'cw67094', to_date('10-JUN-16','DD-MON-RR'));
INSERT into TEST (REPORT_ID, REPORT_NAME, CREATED_BY, CREATION_TIME) values ('2', 'Report2', 'cw67094', to_date('28-DEC-15','DD-MON-RR'));
INSERT into TEST (REPORT_ID, REPORT_NAME, CREATED_BY, CREATION_TIME) values ('3', 'Report3', 'cw67094', to_date('21-DEC-15','DD-MON-RR'));
INSERT into TEST (REPORT_ID, REPORT_NAME, CREATED_BY, CREATION_TIME) values ('4', 'Report4', 'cw67094', to_date('17-DEC-15','DD-MON-RR'));

--TEST--

